name: supbase_lab
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  get_it: ^7.6.7
  flutter_bloc: ^8.1.4
  flutter_dotenv: ^5.1.0
  supabase_flutter: ^2.3.4
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - .env
